#!/bin/sh                                                                       
echo "Cleaning project directory ..."

make distclean
rm -rf Makefile.in aclocal.m4 config.h.in* configure depcomp  install-sh missing autom4te.cache src/Makefile.in doc/Makefile.in test/Makefile.in
echo "rm -rf *~"
find . -name "*~" -exec rm -rf {} \;

echo "Done."


